### ISSUE TITLE
historical trails under dynamic scenarios

### ISSUE THREAD

**Issue by quliang93** [hku-mars/ROG-Map#14]
Thank you for open-sourcing such an amazing work! My question is:
I am attempting to adapt ROG-Map to an autonomous vehicle platform. During testing in scenarios with dynamic obstacles, I observed persistent "historical ghosting" trails behind the dynamic obstacles. Is this issue likely resolvable by adjusting parameters within ROG-Map? Any guidance would be greatly appreciated.
Thanks again for sharing this excellent work!

![Image](https://github.com/user-attachments/assets/f3f0d086-eb0f-4659-9b58-1a3cb6110d01)

**Comment by RENyunfan** [comment]
Hi there, thank you for your interest in our project! You can adjust the parameters for the probability update in the configuration file located at:

https://github.com/hku-mars/ROG-Map/blob/main/examples/rog_map_example/config/pure_ogm.yaml#L69

Here are the relevant parameters:

```yaml
      p_min: 0.12  
      p_miss: 0.49  # Consider reducing this to, for example, 0.4  
      p_free: 0.499 # Consider reducing this to, for example, 0.45  
      p_occ: 0.85  
      p_hit: 0.9  
      p_max: 0.98  
```
Additionally, please note that to eliminate dynamic obstacles, the raycasting process requires background points. If the dataset is recorded in a very open area, there may be no background points available, which could prevent the raycasting process from effectively removing dynamic obstacles.

I am closing this issue for now. If the problems persist and remain unresolved, please feel free to reopen it and share a ROS bag. I’ll try to find some time to investigate further.
